from flask_wtf import Form
from wtforms import IntegerField
from wtforms.validators import DataRequired, Length

class Emuform(Form):
    touhoku1 = IntegerField('touhoku1')
    touhoku2 = IntegerField('touhoku2')
    keio1 = IntegerField('keio1')
    keio2 = IntegerField('keio2')
    waseda1 = IntegerField('waseda1')
    waseda2 = IntegerField('waseda2')
    meikai1 = IntegerField('meikai1')
    meikai2 = IntegerField('meikai2')
    nihon1 = IntegerField('nihon1')
    nihon2 = IntegerField('nihon2')
    tyuou1 = IntegerField('tyuou1')
    tyuou2 = IntegerField('tyuou2')
    hosei1 = IntegerField('hosei1')
    hosei2 = IntegerField('hosei2')
    dosisha1 = IntegerField('dosisha1')
    dosisha2 = IntegerField('dosisha2')
    kyoto1 = IntegerField('kyoto1')
    kyoto2 = IntegerField('kyoto2')
    kwansei1 = IntegerField('kwansei1')
    kwansei2 = IntegerField('kwansei2')
    kansai1 = IntegerField('kansai1')
    kansai2 = IntegerField('kansai2')
    hirosima1 = IntegerField('hirosima1')
    hirosima2 = IntegerField('hirosima2')
    kyshu1 = IntegerField('kyshu1')
    kyshu2 = IntegerField('kyshu2')
